// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package io.streamnative;

public final class PersonEntity {
    private PersonEntity() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface PersonOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Person)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 id = 1;</code>
         * @return The id.
         */
        int getId();

        /**
         * <code>string name = 2;</code>
         * @return The name.
         */
        java.lang.String getName();
        /**
         * <code>string name = 2;</code>
         * @return The bytes for name.
         */
        com.google.protobuf.ByteString
        getNameBytes();

        /**
         * <code>repeated string email = 3;</code>
         * @return A list containing the email.
         */
        java.util.List<java.lang.String>
        getEmailList();
        /**
         * <code>repeated string email = 3;</code>
         * @return The count of email.
         */
        int getEmailCount();
        /**
         * <code>repeated string email = 3;</code>
         * @param index The index of the element to return.
         * @return The email at the given index.
         */
        java.lang.String getEmail(int index);
        /**
         * <code>repeated string email = 3;</code>
         * @param index The index of the value to return.
         * @return The bytes of the email at the given index.
         */
        com.google.protobuf.ByteString
        getEmailBytes(int index);

        /**
         * <code>map&lt;string, string&gt; addresses = 4;</code>
         */
        int getAddressesCount();
        /**
         * <code>map&lt;string, string&gt; addresses = 4;</code>
         */
        boolean containsAddresses(
                java.lang.String key);
        /**
         * Use {@link #getAddressesMap()} instead.
         */
        @java.lang.Deprecated
        java.util.Map<java.lang.String, java.lang.String>
        getAddresses();
        /**
         * <code>map&lt;string, string&gt; addresses = 4;</code>
         */
        java.util.Map<java.lang.String, java.lang.String>
        getAddressesMap();
        /**
         * <code>map&lt;string, string&gt; addresses = 4;</code>
         */

        java.lang.String getAddressesOrDefault(
                java.lang.String key,
                java.lang.String defaultValue);
        /**
         * <code>map&lt;string, string&gt; addresses = 4;</code>
         */

        java.lang.String getAddressesOrThrow(
                java.lang.String key);
    }
    /**
     * Protobuf type {@code Person}
     */
    public static final class Person extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Person)
            PersonOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use Person.newBuilder() to construct.
        private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Person() {
            name_ = "";
            email_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new Person();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private Person(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            id_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        case 26: {
                            java.lang.String s = input.readStringRequireUtf8();
                            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                                email_ = new com.google.protobuf.LazyStringArrayList();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            email_.add(s);
                            break;
                        }
                        case 34: {
                            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                                addresses_ = com.google.protobuf.MapField.newMapField(
                                        AddressesDefaultEntryHolder.defaultEntry);
                                mutable_bitField0_ |= 0x00000002;
                            }
                            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                                    addresses__ = input.readMessage(
                                    AddressesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                            addresses_.getMutableMap().put(
                                    addresses__.getKey(), addresses__.getValue());
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) != 0)) {
                    email_ = email_.getUnmodifiableView();
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return io.streamnative.PersonEntity.internal_static_Person_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        @java.lang.Override
        protected com.google.protobuf.MapField internalGetMapField(
                int number) {
            switch (number) {
                case 4:
                    return internalGetAddresses();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }
        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return io.streamnative.PersonEntity.internal_static_Person_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            io.streamnative.PersonEntity.Person.class, io.streamnative.PersonEntity.Person.Builder.class);
        }

        /**
         * Protobuf enum {@code Person.PhoneType}
         */
        public enum PhoneType
                implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>MOBILE = 0;</code>
             */
            MOBILE(0),
            /**
             * <code>HOME = 1;</code>
             */
            HOME(1),
            /**
             * <code>WORK = 2;</code>
             */
            WORK(2),
            UNRECOGNIZED(-1),
            ;

            /**
             * <code>MOBILE = 0;</code>
             */
            public static final int MOBILE_VALUE = 0;
            /**
             * <code>HOME = 1;</code>
             */
            public static final int HOME_VALUE = 1;
            /**
             * <code>WORK = 2;</code>
             */
            public static final int WORK_VALUE = 2;


            public final int getNumber() {
                if (this == UNRECOGNIZED) {
                    throw new java.lang.IllegalArgumentException(
                            "Can't get the number of an unknown enum value.");
                }
                return value;
            }

            /**
             * @param value The numeric wire value of the corresponding enum entry.
             * @return The enum associated with the given numeric wire value.
             * @deprecated Use {@link #forNumber(int)} instead.
             */
            @java.lang.Deprecated
            public static PhoneType valueOf(int value) {
                return forNumber(value);
            }

            /**
             * @param value The numeric wire value of the corresponding enum entry.
             * @return The enum associated with the given numeric wire value.
             */
            public static PhoneType forNumber(int value) {
                switch (value) {
                    case 0: return MOBILE;
                    case 1: return HOME;
                    case 2: return WORK;
                    default: return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
            internalGetValueMap() {
                return internalValueMap;
            }
            private static final com.google.protobuf.Internal.EnumLiteMap<
                    PhoneType> internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
                        public PhoneType findValueByNumber(int number) {
                            return PhoneType.forNumber(number);
                        }
                    };

            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
                if (this == UNRECOGNIZED) {
                    throw new java.lang.IllegalStateException(
                            "Can't get the descriptor of an unrecognized enum value.");
                }
                return getDescriptor().getValues().get(ordinal());
            }
            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }
            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
                return io.streamnative.PersonEntity.Person.getDescriptor().getEnumTypes().get(0);
            }

            private static final PhoneType[] VALUES = values();

            public static PhoneType valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                if (desc.getIndex() == -1) {
                    return UNRECOGNIZED;
                }
                return VALUES[desc.getIndex()];
            }

            private final int value;

            private PhoneType(int value) {
                this.value = value;
            }

            // @@protoc_insertion_point(enum_scope:Person.PhoneType)
        }

        public interface PhoneNumberOrBuilder extends
                // @@protoc_insertion_point(interface_extends:Person.PhoneNumber)
                com.google.protobuf.MessageOrBuilder {

            /**
             * <code>string number = 1;</code>
             * @return The number.
             */
            java.lang.String getNumber();
            /**
             * <code>string number = 1;</code>
             * @return The bytes for number.
             */
            com.google.protobuf.ByteString
            getNumberBytes();

            /**
             * <code>.Person.PhoneType type = 2;</code>
             * @return The enum numeric value on the wire for type.
             */
            int getTypeValue();
            /**
             * <code>.Person.PhoneType type = 2;</code>
             * @return The type.
             */
            io.streamnative.PersonEntity.Person.PhoneType getType();
        }
        /**
         * Protobuf type {@code Person.PhoneNumber}
         */
        public static final class PhoneNumber extends
                com.google.protobuf.GeneratedMessageV3 implements
                // @@protoc_insertion_point(message_implements:Person.PhoneNumber)
                PhoneNumberOrBuilder {
            private static final long serialVersionUID = 0L;
            // Use PhoneNumber.newBuilder() to construct.
            private PhoneNumber(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
                super(builder);
            }
            private PhoneNumber() {
                number_ = "";
                type_ = 0;
            }

            @java.lang.Override
            @SuppressWarnings({"unused"})
            protected java.lang.Object newInstance(
                    UnusedPrivateParameter unused) {
                return new PhoneNumber();
            }

            @java.lang.Override
            public final com.google.protobuf.UnknownFieldSet
            getUnknownFields() {
                return this.unknownFields;
            }
            private PhoneNumber(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                this();
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder();
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                java.lang.String s = input.readStringRequireUtf8();

                                number_ = s;
                                break;
                            }
                            case 16: {
                                int rawValue = input.readEnum();

                                type_ = rawValue;
                                break;
                            }
                            default: {
                                if (!parseUnknownField(
                                        input, unknownFields, extensionRegistry, tag)) {
                                    done = true;
                                }
                                break;
                            }
                        }
                    }
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(this);
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(
                            e).setUnfinishedMessage(this);
                } finally {
                    this.unknownFields = unknownFields.build();
                    makeExtensionsImmutable();
                }
            }
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return io.streamnative.PersonEntity.internal_static_Person_PhoneNumber_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return io.streamnative.PersonEntity.internal_static_Person_PhoneNumber_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                io.streamnative.PersonEntity.Person.PhoneNumber.class, io.streamnative.PersonEntity.Person.PhoneNumber.Builder.class);
            }

            public static final int NUMBER_FIELD_NUMBER = 1;
            private volatile java.lang.Object number_;
            /**
             * <code>string number = 1;</code>
             * @return The number.
             */
            @java.lang.Override
            public java.lang.String getNumber() {
                java.lang.Object ref = number_;
                if (ref instanceof java.lang.String) {
                    return (java.lang.String) ref;
                } else {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    number_ = s;
                    return s;
                }
            }
            /**
             * <code>string number = 1;</code>
             * @return The bytes for number.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString
            getNumberBytes() {
                java.lang.Object ref = number_;
                if (ref instanceof java.lang.String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    number_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            public static final int TYPE_FIELD_NUMBER = 2;
            private int type_;
            /**
             * <code>.Person.PhoneType type = 2;</code>
             * @return The enum numeric value on the wire for type.
             */
            @java.lang.Override public int getTypeValue() {
                return type_;
            }
            /**
             * <code>.Person.PhoneType type = 2;</code>
             * @return The type.
             */
            @java.lang.Override public io.streamnative.PersonEntity.Person.PhoneType getType() {
                @SuppressWarnings("deprecation")
                io.streamnative.PersonEntity.Person.PhoneType result = io.streamnative.PersonEntity.Person.PhoneType.valueOf(type_);
                return result == null ? io.streamnative.PersonEntity.Person.PhoneType.UNRECOGNIZED : result;
            }

            private byte memoizedIsInitialized = -1;
            @java.lang.Override
            public final boolean isInitialized() {
                byte isInitialized = memoizedIsInitialized;
                if (isInitialized == 1) return true;
                if (isInitialized == 0) return false;

                memoizedIsInitialized = 1;
                return true;
            }

            @java.lang.Override
            public void writeTo(com.google.protobuf.CodedOutputStream output)
                    throws java.io.IOException {
                if (!getNumberBytes().isEmpty()) {
                    com.google.protobuf.GeneratedMessageV3.writeString(output, 1, number_);
                }
                if (type_ != io.streamnative.PersonEntity.Person.PhoneType.MOBILE.getNumber()) {
                    output.writeEnum(2, type_);
                }
                unknownFields.writeTo(output);
            }

            @java.lang.Override
            public int getSerializedSize() {
                int size = memoizedSize;
                if (size != -1) return size;

                size = 0;
                if (!getNumberBytes().isEmpty()) {
                    size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, number_);
                }
                if (type_ != io.streamnative.PersonEntity.Person.PhoneType.MOBILE.getNumber()) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeEnumSize(2, type_);
                }
                size += unknownFields.getSerializedSize();
                memoizedSize = size;
                return size;
            }

            @java.lang.Override
            public boolean equals(final java.lang.Object obj) {
                if (obj == this) {
                    return true;
                }
                if (!(obj instanceof io.streamnative.PersonEntity.Person.PhoneNumber)) {
                    return super.equals(obj);
                }
                io.streamnative.PersonEntity.Person.PhoneNumber other = (io.streamnative.PersonEntity.Person.PhoneNumber) obj;

                if (!getNumber()
                        .equals(other.getNumber())) return false;
                if (type_ != other.type_) return false;
                if (!unknownFields.equals(other.unknownFields)) return false;
                return true;
            }

            @java.lang.Override
            public int hashCode() {
                if (memoizedHashCode != 0) {
                    return memoizedHashCode;
                }
                int hash = 41;
                hash = (19 * hash) + getDescriptor().hashCode();
                hash = (37 * hash) + NUMBER_FIELD_NUMBER;
                hash = (53 * hash) + getNumber().hashCode();
                hash = (37 * hash) + TYPE_FIELD_NUMBER;
                hash = (53 * hash) + type_;
                hash = (29 * hash) + unknownFields.hashCode();
                memoizedHashCode = hash;
                return hash;
            }

            public static io.streamnative.PersonEntity.Person.PhoneNumber parseFrom(
                    java.nio.ByteBuffer data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }
            public static io.streamnative.PersonEntity.Person.PhoneNumber parseFrom(
                    java.nio.ByteBuffer data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }
            public static io.streamnative.PersonEntity.Person.PhoneNumber parseFrom(
                    com.google.protobuf.ByteString data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }
            public static io.streamnative.PersonEntity.Person.PhoneNumber parseFrom(
                    com.google.protobuf.ByteString data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }
            public static io.streamnative.PersonEntity.Person.PhoneNumber parseFrom(byte[] data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }
            public static io.streamnative.PersonEntity.Person.PhoneNumber parseFrom(
                    byte[] data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }
            public static io.streamnative.PersonEntity.Person.PhoneNumber parseFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input);
            }
            public static io.streamnative.PersonEntity.Person.PhoneNumber parseFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input, extensionRegistry);
            }
            public static io.streamnative.PersonEntity.Person.PhoneNumber parseDelimitedFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseDelimitedWithIOException(PARSER, input);
            }
            public static io.streamnative.PersonEntity.Person.PhoneNumber parseDelimitedFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
            }
            public static io.streamnative.PersonEntity.Person.PhoneNumber parseFrom(
                    com.google.protobuf.CodedInputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input);
            }
            public static io.streamnative.PersonEntity.Person.PhoneNumber parseFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input, extensionRegistry);
            }

            @java.lang.Override
            public Builder newBuilderForType() { return newBuilder(); }
            public static Builder newBuilder() {
                return DEFAULT_INSTANCE.toBuilder();
            }
            public static Builder newBuilder(io.streamnative.PersonEntity.Person.PhoneNumber prototype) {
                return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
            }
            @java.lang.Override
            public Builder toBuilder() {
                return this == DEFAULT_INSTANCE
                        ? new Builder() : new Builder().mergeFrom(this);
            }

            @java.lang.Override
            protected Builder newBuilderForType(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                Builder builder = new Builder(parent);
                return builder;
            }
            /**
             * Protobuf type {@code Person.PhoneNumber}
             */
            public static final class Builder extends
                    com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                    // @@protoc_insertion_point(builder_implements:Person.PhoneNumber)
                    io.streamnative.PersonEntity.Person.PhoneNumberOrBuilder {
                public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
                    return io.streamnative.PersonEntity.internal_static_Person_PhoneNumber_descriptor;
                }

                @java.lang.Override
                protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
                internalGetFieldAccessorTable() {
                    return io.streamnative.PersonEntity.internal_static_Person_PhoneNumber_fieldAccessorTable
                            .ensureFieldAccessorsInitialized(
                                    io.streamnative.PersonEntity.Person.PhoneNumber.class, io.streamnative.PersonEntity.Person.PhoneNumber.Builder.class);
                }

                // Construct using io.streamnative.PersonEntity.Person.PhoneNumber.newBuilder()
                private Builder() {
                    maybeForceBuilderInitialization();
                }

                private Builder(
                        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                    super(parent);
                    maybeForceBuilderInitialization();
                }
                private void maybeForceBuilderInitialization() {
                    if (com.google.protobuf.GeneratedMessageV3
                            .alwaysUseFieldBuilders) {
                    }
                }
                @java.lang.Override
                public Builder clear() {
                    super.clear();
                    number_ = "";

                    type_ = 0;

                    return this;
                }

                @java.lang.Override
                public com.google.protobuf.Descriptors.Descriptor
                getDescriptorForType() {
                    return io.streamnative.PersonEntity.internal_static_Person_PhoneNumber_descriptor;
                }

                @java.lang.Override
                public io.streamnative.PersonEntity.Person.PhoneNumber getDefaultInstanceForType() {
                    return io.streamnative.PersonEntity.Person.PhoneNumber.getDefaultInstance();
                }

                @java.lang.Override
                public io.streamnative.PersonEntity.Person.PhoneNumber build() {
                    io.streamnative.PersonEntity.Person.PhoneNumber result = buildPartial();
                    if (!result.isInitialized()) {
                        throw newUninitializedMessageException(result);
                    }
                    return result;
                }

                @java.lang.Override
                public io.streamnative.PersonEntity.Person.PhoneNumber buildPartial() {
                    io.streamnative.PersonEntity.Person.PhoneNumber result = new io.streamnative.PersonEntity.Person.PhoneNumber(this);
                    result.number_ = number_;
                    result.type_ = type_;
                    onBuilt();
                    return result;
                }

                @java.lang.Override
                public Builder clone() {
                    return super.clone();
                }
                @java.lang.Override
                public Builder setField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        java.lang.Object value) {
                    return super.setField(field, value);
                }
                @java.lang.Override
                public Builder clearField(
                        com.google.protobuf.Descriptors.FieldDescriptor field) {
                    return super.clearField(field);
                }
                @java.lang.Override
                public Builder clearOneof(
                        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                    return super.clearOneof(oneof);
                }
                @java.lang.Override
                public Builder setRepeatedField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        int index, java.lang.Object value) {
                    return super.setRepeatedField(field, index, value);
                }
                @java.lang.Override
                public Builder addRepeatedField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        java.lang.Object value) {
                    return super.addRepeatedField(field, value);
                }
                @java.lang.Override
                public Builder mergeFrom(com.google.protobuf.Message other) {
                    if (other instanceof io.streamnative.PersonEntity.Person.PhoneNumber) {
                        return mergeFrom((io.streamnative.PersonEntity.Person.PhoneNumber)other);
                    } else {
                        super.mergeFrom(other);
                        return this;
                    }
                }

                public Builder mergeFrom(io.streamnative.PersonEntity.Person.PhoneNumber other) {
                    if (other == io.streamnative.PersonEntity.Person.PhoneNumber.getDefaultInstance()) return this;
                    if (!other.getNumber().isEmpty()) {
                        number_ = other.number_;
                        onChanged();
                    }
                    if (other.type_ != 0) {
                        setTypeValue(other.getTypeValue());
                    }
                    this.mergeUnknownFields(other.unknownFields);
                    onChanged();
                    return this;
                }

                @java.lang.Override
                public final boolean isInitialized() {
                    return true;
                }

                @java.lang.Override
                public Builder mergeFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
                    io.streamnative.PersonEntity.Person.PhoneNumber parsedMessage = null;
                    try {
                        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        parsedMessage = (io.streamnative.PersonEntity.Person.PhoneNumber) e.getUnfinishedMessage();
                        throw e.unwrapIOException();
                    } finally {
                        if (parsedMessage != null) {
                            mergeFrom(parsedMessage);
                        }
                    }
                    return this;
                }

                private java.lang.Object number_ = "";
                /**
                 * <code>string number = 1;</code>
                 * @return The number.
                 */
                public java.lang.String getNumber() {
                    java.lang.Object ref = number_;
                    if (!(ref instanceof java.lang.String)) {
                        com.google.protobuf.ByteString bs =
                                (com.google.protobuf.ByteString) ref;
                        java.lang.String s = bs.toStringUtf8();
                        number_ = s;
                        return s;
                    } else {
                        return (java.lang.String) ref;
                    }
                }
                /**
                 * <code>string number = 1;</code>
                 * @return The bytes for number.
                 */
                public com.google.protobuf.ByteString
                getNumberBytes() {
                    java.lang.Object ref = number_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b =
                                com.google.protobuf.ByteString.copyFromUtf8(
                                        (java.lang.String) ref);
                        number_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }
                /**
                 * <code>string number = 1;</code>
                 * @param value The number to set.
                 * @return This builder for chaining.
                 */
                public Builder setNumber(
                        java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }

                    number_ = value;
                    onChanged();
                    return this;
                }
                /**
                 * <code>string number = 1;</code>
                 * @return This builder for chaining.
                 */
                public Builder clearNumber() {

                    number_ = getDefaultInstance().getNumber();
                    onChanged();
                    return this;
                }
                /**
                 * <code>string number = 1;</code>
                 * @param value The bytes for number to set.
                 * @return This builder for chaining.
                 */
                public Builder setNumberBytes(
                        com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    checkByteStringIsUtf8(value);

                    number_ = value;
                    onChanged();
                    return this;
                }

                private int type_ = 0;
                /**
                 * <code>.Person.PhoneType type = 2;</code>
                 * @return The enum numeric value on the wire for type.
                 */
                @java.lang.Override public int getTypeValue() {
                    return type_;
                }
                /**
                 * <code>.Person.PhoneType type = 2;</code>
                 * @param value The enum numeric value on the wire for type to set.
                 * @return This builder for chaining.
                 */
                public Builder setTypeValue(int value) {

                    type_ = value;
                    onChanged();
                    return this;
                }
                /**
                 * <code>.Person.PhoneType type = 2;</code>
                 * @return The type.
                 */
                @java.lang.Override
                public io.streamnative.PersonEntity.Person.PhoneType getType() {
                    @SuppressWarnings("deprecation")
                    io.streamnative.PersonEntity.Person.PhoneType result = io.streamnative.PersonEntity.Person.PhoneType.valueOf(type_);
                    return result == null ? io.streamnative.PersonEntity.Person.PhoneType.UNRECOGNIZED : result;
                }
                /**
                 * <code>.Person.PhoneType type = 2;</code>
                 * @param value The type to set.
                 * @return This builder for chaining.
                 */
                public Builder setType(io.streamnative.PersonEntity.Person.PhoneType value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }

                    type_ = value.getNumber();
                    onChanged();
                    return this;
                }
                /**
                 * <code>.Person.PhoneType type = 2;</code>
                 * @return This builder for chaining.
                 */
                public Builder clearType() {

                    type_ = 0;
                    onChanged();
                    return this;
                }
                @java.lang.Override
                public final Builder setUnknownFields(
                        final com.google.protobuf.UnknownFieldSet unknownFields) {
                    return super.setUnknownFields(unknownFields);
                }

                @java.lang.Override
                public final Builder mergeUnknownFields(
                        final com.google.protobuf.UnknownFieldSet unknownFields) {
                    return super.mergeUnknownFields(unknownFields);
                }


                // @@protoc_insertion_point(builder_scope:Person.PhoneNumber)
            }

            // @@protoc_insertion_point(class_scope:Person.PhoneNumber)
            private static final io.streamnative.PersonEntity.Person.PhoneNumber DEFAULT_INSTANCE;
            static {
                DEFAULT_INSTANCE = new io.streamnative.PersonEntity.Person.PhoneNumber();
            }

            public static io.streamnative.PersonEntity.Person.PhoneNumber getDefaultInstance() {
                return DEFAULT_INSTANCE;
            }

            private static final com.google.protobuf.Parser<PhoneNumber>
                    PARSER = new com.google.protobuf.AbstractParser<PhoneNumber>() {
                @java.lang.Override
                public PhoneNumber parsePartialFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
                    return new PhoneNumber(input, extensionRegistry);
                }
            };

            public static com.google.protobuf.Parser<PhoneNumber> parser() {
                return PARSER;
            }

            @java.lang.Override
            public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
                return PARSER;
            }

            @java.lang.Override
            public io.streamnative.PersonEntity.Person.PhoneNumber getDefaultInstanceForType() {
                return DEFAULT_INSTANCE;
            }

        }

        public static final int ID_FIELD_NUMBER = 1;
        private int id_;
        /**
         * <code>int32 id = 1;</code>
         * @return The id.
         */
        @java.lang.Override
        public int getId() {
            return id_;
        }

        public static final int NAME_FIELD_NUMBER = 2;
        private volatile java.lang.Object name_;
        /**
         * <code>string name = 2;</code>
         * @return The name.
         */
        @java.lang.Override
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }
        /**
         * <code>string name = 2;</code>
         * @return The bytes for name.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int EMAIL_FIELD_NUMBER = 3;
        private com.google.protobuf.LazyStringList email_;
        /**
         * <code>repeated string email = 3;</code>
         * @return A list containing the email.
         */
        public com.google.protobuf.ProtocolStringList
        getEmailList() {
            return email_;
        }
        /**
         * <code>repeated string email = 3;</code>
         * @return The count of email.
         */
        public int getEmailCount() {
            return email_.size();
        }
        /**
         * <code>repeated string email = 3;</code>
         * @param index The index of the element to return.
         * @return The email at the given index.
         */
        public java.lang.String getEmail(int index) {
            return email_.get(index);
        }
        /**
         * <code>repeated string email = 3;</code>
         * @param index The index of the value to return.
         * @return The bytes of the email at the given index.
         */
        public com.google.protobuf.ByteString
        getEmailBytes(int index) {
            return email_.getByteString(index);
        }

        public static final int ADDRESSES_FIELD_NUMBER = 4;
        private static final class AddressesDefaultEntryHolder {
            static final com.google.protobuf.MapEntry<
                    java.lang.String, java.lang.String> defaultEntry =
                    com.google.protobuf.MapEntry
                            .<java.lang.String, java.lang.String>newDefaultInstance(
                                    io.streamnative.PersonEntity.internal_static_Person_AddressesEntry_descriptor,
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "",
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "");
        }
        private com.google.protobuf.MapField<
                java.lang.String, java.lang.String> addresses_;
        private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetAddresses() {
            if (addresses_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        AddressesDefaultEntryHolder.defaultEntry);
            }
            return addresses_;
        }

        public int getAddressesCount() {
            return internalGetAddresses().getMap().size();
        }
        /**
         * <code>map&lt;string, string&gt; addresses = 4;</code>
         */

        @java.lang.Override
        public boolean containsAddresses(
                java.lang.String key) {
            if (key == null) { throw new java.lang.NullPointerException(); }
            return internalGetAddresses().getMap().containsKey(key);
        }
        /**
         * Use {@link #getAddressesMap()} instead.
         */
        @java.lang.Override
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, java.lang.String> getAddresses() {
            return getAddressesMap();
        }
        /**
         * <code>map&lt;string, string&gt; addresses = 4;</code>
         */
        @java.lang.Override

        public java.util.Map<java.lang.String, java.lang.String> getAddressesMap() {
            return internalGetAddresses().getMap();
        }
        /**
         * <code>map&lt;string, string&gt; addresses = 4;</code>
         */
        @java.lang.Override

        public java.lang.String getAddressesOrDefault(
                java.lang.String key,
                java.lang.String defaultValue) {
            if (key == null) { throw new java.lang.NullPointerException(); }
            java.util.Map<java.lang.String, java.lang.String> map =
                    internalGetAddresses().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }
        /**
         * <code>map&lt;string, string&gt; addresses = 4;</code>
         */
        @java.lang.Override

        public java.lang.String getAddressesOrThrow(
                java.lang.String key) {
            if (key == null) { throw new java.lang.NullPointerException(); }
            java.util.Map<java.lang.String, java.lang.String> map =
                    internalGetAddresses().getMap();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (id_ != 0) {
                output.writeInt32(1, id_);
            }
            if (!getNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
            }
            for (int i = 0; i < email_.size(); i++) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_.getRaw(i));
            }
            com.google.protobuf.GeneratedMessageV3
                    .serializeStringMapTo(
                            output,
                            internalGetAddresses(),
                            AddressesDefaultEntryHolder.defaultEntry,
                            4);
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (id_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, id_);
            }
            if (!getNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
            }
            {
                int dataSize = 0;
                for (int i = 0; i < email_.size(); i++) {
                    dataSize += computeStringSizeNoTag(email_.getRaw(i));
                }
                size += dataSize;
                size += 1 * getEmailList().size();
            }
            for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
                    : internalGetAddresses().getMap().entrySet()) {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                        addresses__ = AddressesDefaultEntryHolder.defaultEntry.newBuilderForType()
                        .setKey(entry.getKey())
                        .setValue(entry.getValue())
                        .build();
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(4, addresses__);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof io.streamnative.PersonEntity.Person)) {
                return super.equals(obj);
            }
            io.streamnative.PersonEntity.Person other = (io.streamnative.PersonEntity.Person) obj;

            if (getId()
                    != other.getId()) return false;
            if (!getName()
                    .equals(other.getName())) return false;
            if (!getEmailList()
                    .equals(other.getEmailList())) return false;
            if (!internalGetAddresses().equals(
                    other.internalGetAddresses())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + getId();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            if (getEmailCount() > 0) {
                hash = (37 * hash) + EMAIL_FIELD_NUMBER;
                hash = (53 * hash) + getEmailList().hashCode();
            }
            if (!internalGetAddresses().getMap().isEmpty()) {
                hash = (37 * hash) + ADDRESSES_FIELD_NUMBER;
                hash = (53 * hash) + internalGetAddresses().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static io.streamnative.PersonEntity.Person parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static io.streamnative.PersonEntity.Person parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static io.streamnative.PersonEntity.Person parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static io.streamnative.PersonEntity.Person parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static io.streamnative.PersonEntity.Person parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static io.streamnative.PersonEntity.Person parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static io.streamnative.PersonEntity.Person parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static io.streamnative.PersonEntity.Person parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static io.streamnative.PersonEntity.Person parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static io.streamnative.PersonEntity.Person parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static io.streamnative.PersonEntity.Person parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static io.streamnative.PersonEntity.Person parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(io.streamnative.PersonEntity.Person prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code Person}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Person)
                io.streamnative.PersonEntity.PersonOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return io.streamnative.PersonEntity.internal_static_Person_descriptor;
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMapField(
                    int number) {
                switch (number) {
                    case 4:
                        return internalGetAddresses();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }
            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMutableMapField(
                    int number) {
                switch (number) {
                    case 4:
                        return internalGetMutableAddresses();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }
            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return io.streamnative.PersonEntity.internal_static_Person_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                io.streamnative.PersonEntity.Person.class, io.streamnative.PersonEntity.Person.Builder.class);
            }

            // Construct using io.streamnative.PersonEntity.Person.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                id_ = 0;

                name_ = "";

                email_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000001);
                internalGetMutableAddresses().clear();
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return io.streamnative.PersonEntity.internal_static_Person_descriptor;
            }

            @java.lang.Override
            public io.streamnative.PersonEntity.Person getDefaultInstanceForType() {
                return io.streamnative.PersonEntity.Person.getDefaultInstance();
            }

            @java.lang.Override
            public io.streamnative.PersonEntity.Person build() {
                io.streamnative.PersonEntity.Person result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public io.streamnative.PersonEntity.Person buildPartial() {
                io.streamnative.PersonEntity.Person result = new io.streamnative.PersonEntity.Person(this);
                int from_bitField0_ = bitField0_;
                result.id_ = id_;
                result.name_ = name_;
                if (((bitField0_ & 0x00000001) != 0)) {
                    email_ = email_.getUnmodifiableView();
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.email_ = email_;
                result.addresses_ = internalGetAddresses();
                result.addresses_.makeImmutable();
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof io.streamnative.PersonEntity.Person) {
                    return mergeFrom((io.streamnative.PersonEntity.Person)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(io.streamnative.PersonEntity.Person other) {
                if (other == io.streamnative.PersonEntity.Person.getDefaultInstance()) return this;
                if (other.getId() != 0) {
                    setId(other.getId());
                }
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    onChanged();
                }
                if (!other.email_.isEmpty()) {
                    if (email_.isEmpty()) {
                        email_ = other.email_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureEmailIsMutable();
                        email_.addAll(other.email_);
                    }
                    onChanged();
                }
                internalGetMutableAddresses().mergeFrom(
                        other.internalGetAddresses());
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                io.streamnative.PersonEntity.Person parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (io.streamnative.PersonEntity.Person) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private int id_ ;
            /**
             * <code>int32 id = 1;</code>
             * @return The id.
             */
            @java.lang.Override
            public int getId() {
                return id_;
            }
            /**
             * <code>int32 id = 1;</code>
             * @param value The id to set.
             * @return This builder for chaining.
             */
            public Builder setId(int value) {

                id_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>int32 id = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearId() {

                id_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object name_ = "";
            /**
             * <code>string name = 2;</code>
             * @return The name.
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string name = 2;</code>
             * @return The bytes for name.
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string name = 2;</code>
             * @param value The name to set.
             * @return This builder for chaining.
             */
            public Builder setName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string name = 2;</code>
             * @return This builder for chaining.
             */
            public Builder clearName() {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }
            /**
             * <code>string name = 2;</code>
             * @param value The bytes for name to set.
             * @return This builder for chaining.
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.LazyStringList email_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            private void ensureEmailIsMutable() {
                if (!((bitField0_ & 0x00000001) != 0)) {
                    email_ = new com.google.protobuf.LazyStringArrayList(email_);
                    bitField0_ |= 0x00000001;
                }
            }
            /**
             * <code>repeated string email = 3;</code>
             * @return A list containing the email.
             */
            public com.google.protobuf.ProtocolStringList
            getEmailList() {
                return email_.getUnmodifiableView();
            }
            /**
             * <code>repeated string email = 3;</code>
             * @return The count of email.
             */
            public int getEmailCount() {
                return email_.size();
            }
            /**
             * <code>repeated string email = 3;</code>
             * @param index The index of the element to return.
             * @return The email at the given index.
             */
            public java.lang.String getEmail(int index) {
                return email_.get(index);
            }
            /**
             * <code>repeated string email = 3;</code>
             * @param index The index of the value to return.
             * @return The bytes of the email at the given index.
             */
            public com.google.protobuf.ByteString
            getEmailBytes(int index) {
                return email_.getByteString(index);
            }
            /**
             * <code>repeated string email = 3;</code>
             * @param index The index to set the value at.
             * @param value The email to set.
             * @return This builder for chaining.
             */
            public Builder setEmail(
                    int index, java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureEmailIsMutable();
                email_.set(index, value);
                onChanged();
                return this;
            }
            /**
             * <code>repeated string email = 3;</code>
             * @param value The email to add.
             * @return This builder for chaining.
             */
            public Builder addEmail(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureEmailIsMutable();
                email_.add(value);
                onChanged();
                return this;
            }
            /**
             * <code>repeated string email = 3;</code>
             * @param values The email to add.
             * @return This builder for chaining.
             */
            public Builder addAllEmail(
                    java.lang.Iterable<java.lang.String> values) {
                ensureEmailIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, email_);
                onChanged();
                return this;
            }
            /**
             * <code>repeated string email = 3;</code>
             * @return This builder for chaining.
             */
            public Builder clearEmail() {
                email_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }
            /**
             * <code>repeated string email = 3;</code>
             * @param value The bytes of the email to add.
             * @return This builder for chaining.
             */
            public Builder addEmailBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                ensureEmailIsMutable();
                email_.add(value);
                onChanged();
                return this;
            }

            private com.google.protobuf.MapField<
                    java.lang.String, java.lang.String> addresses_;
            private com.google.protobuf.MapField<java.lang.String, java.lang.String>
            internalGetAddresses() {
                if (addresses_ == null) {
                    return com.google.protobuf.MapField.emptyMapField(
                            AddressesDefaultEntryHolder.defaultEntry);
                }
                return addresses_;
            }
            private com.google.protobuf.MapField<java.lang.String, java.lang.String>
            internalGetMutableAddresses() {
                onChanged();;
                if (addresses_ == null) {
                    addresses_ = com.google.protobuf.MapField.newMapField(
                            AddressesDefaultEntryHolder.defaultEntry);
                }
                if (!addresses_.isMutable()) {
                    addresses_ = addresses_.copy();
                }
                return addresses_;
            }

            public int getAddressesCount() {
                return internalGetAddresses().getMap().size();
            }
            /**
             * <code>map&lt;string, string&gt; addresses = 4;</code>
             */

            @java.lang.Override
            public boolean containsAddresses(
                    java.lang.String key) {
                if (key == null) { throw new java.lang.NullPointerException(); }
                return internalGetAddresses().getMap().containsKey(key);
            }
            /**
             * Use {@link #getAddressesMap()} instead.
             */
            @java.lang.Override
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, java.lang.String> getAddresses() {
                return getAddressesMap();
            }
            /**
             * <code>map&lt;string, string&gt; addresses = 4;</code>
             */
            @java.lang.Override

            public java.util.Map<java.lang.String, java.lang.String> getAddressesMap() {
                return internalGetAddresses().getMap();
            }
            /**
             * <code>map&lt;string, string&gt; addresses = 4;</code>
             */
            @java.lang.Override

            public java.lang.String getAddressesOrDefault(
                    java.lang.String key,
                    java.lang.String defaultValue) {
                if (key == null) { throw new java.lang.NullPointerException(); }
                java.util.Map<java.lang.String, java.lang.String> map =
                        internalGetAddresses().getMap();
                return map.containsKey(key) ? map.get(key) : defaultValue;
            }
            /**
             * <code>map&lt;string, string&gt; addresses = 4;</code>
             */
            @java.lang.Override

            public java.lang.String getAddressesOrThrow(
                    java.lang.String key) {
                if (key == null) { throw new java.lang.NullPointerException(); }
                java.util.Map<java.lang.String, java.lang.String> map =
                        internalGetAddresses().getMap();
                if (!map.containsKey(key)) {
                    throw new java.lang.IllegalArgumentException();
                }
                return map.get(key);
            }

            public Builder clearAddresses() {
                internalGetMutableAddresses().getMutableMap()
                        .clear();
                return this;
            }
            /**
             * <code>map&lt;string, string&gt; addresses = 4;</code>
             */

            public Builder removeAddresses(
                    java.lang.String key) {
                if (key == null) { throw new java.lang.NullPointerException(); }
                internalGetMutableAddresses().getMutableMap()
                        .remove(key);
                return this;
            }
            /**
             * Use alternate mutation accessors instead.
             */
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, java.lang.String>
            getMutableAddresses() {
                return internalGetMutableAddresses().getMutableMap();
            }
            /**
             * <code>map&lt;string, string&gt; addresses = 4;</code>
             */
            public Builder putAddresses(
                    java.lang.String key,
                    java.lang.String value) {
                if (key == null) { throw new java.lang.NullPointerException(); }
                if (value == null) { throw new java.lang.NullPointerException(); }
                internalGetMutableAddresses().getMutableMap()
                        .put(key, value);
                return this;
            }
            /**
             * <code>map&lt;string, string&gt; addresses = 4;</code>
             */

            public Builder putAllAddresses(
                    java.util.Map<java.lang.String, java.lang.String> values) {
                internalGetMutableAddresses().getMutableMap()
                        .putAll(values);
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Person)
        }

        // @@protoc_insertion_point(class_scope:Person)
        private static final io.streamnative.PersonEntity.Person DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new io.streamnative.PersonEntity.Person();
        }

        public static io.streamnative.PersonEntity.Person getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Person>
                PARSER = new com.google.protobuf.AbstractParser<Person>() {
            @java.lang.Override
            public Person parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Person(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Person> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Person> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public io.streamnative.PersonEntity.Person getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Person_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Person_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Person_AddressesEntry_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Person_AddressesEntry_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Person_PhoneNumber_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Person_PhoneNumber_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\014person.proto\"\373\001\n\006Person\022\n\n\002id\030\001 \001(\005\022\014\n" +
                        "\004name\030\002 \001(\t\022\r\n\005email\030\003 \003(\t\022)\n\taddresses\030" +
                        "\004 \003(\0132\026.Person.AddressesEntry\0320\n\016Address" +
                        "esEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032" +
                        ">\n\013PhoneNumber\022\016\n\006number\030\001 \001(\t\022\037\n\004type\030\002" +
                        " \001(\0162\021.Person.PhoneType\"+\n\tPhoneType\022\n\n\006" +
                        "MOBILE\020\000\022\010\n\004HOME\020\001\022\010\n\004WORK\020\002B\037\n\017io.strea" +
                        "mnativeB\014PersonEntityb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        });
        internal_static_Person_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_Person_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Person_descriptor,
                new java.lang.String[] { "Id", "Name", "Email", "Addresses", });
        internal_static_Person_AddressesEntry_descriptor =
                internal_static_Person_descriptor.getNestedTypes().get(0);
        internal_static_Person_AddressesEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Person_AddressesEntry_descriptor,
                new java.lang.String[] { "Key", "Value", });
        internal_static_Person_PhoneNumber_descriptor =
                internal_static_Person_descriptor.getNestedTypes().get(1);
        internal_static_Person_PhoneNumber_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Person_PhoneNumber_descriptor,
                new java.lang.String[] { "Number", "Type", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
